Спринт 9. Попытка 1.
NastasyaRosh/java-filmorate pull request #1
Opened 2022-11-13 14:03 UTC by NastasyaRosh

2022-11-13 19:38 UTC, sergeymamonov requested changes

2022-11-13 19:38 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/TestFilmController.java
> +        Film withFalseDate = Film.builder().name("Фильм").description("Ложная дата.").releaseDate(LocalDate.of(1895, 12, 27)).duration(90).build();
Обратите внимание, что в каждом тесте создается фильм. То есть можно вынести создание фильма в метод beforeEach() и там создавать корректный филь, а в каждом тесте менять одно из полей у уже созданного фильма на некорректное значение.

2022-11-13 19:38 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private HashMap<Integer, Film> films = new HashMap<>();
Нужно стараться определять все на уровне интерфейсов. Здесь это можно сделать изменив на Map<Integer, Film> films

2022-11-13 19:38 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final LocalDate firstFilm = LocalDate.of(1895, 12, 28);
Эту переменную можно определить как константу, дав ей соответствующие модификаторы и написание имени с помощью заглавных букв.

2022-11-13 19:38 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (film.getReleaseDate().isBefore(firstFilm)) {
Лучше выделить валидацию в отдельный метод. И тогде будет лаконичнее
addFilm(@Valid @RequestBody Film film) {
validate(film);
films.put(setId(film), film);
...

Else не нужен, так как если будет ошибка, то код дальше throw не пойдет, если ошибка нигде не обрабатывается.

Для остальных методов аналогично.

2022-11-13 19:38 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private HashMap<Integer, User> users = new HashMap<>();
Классы для юзера аналогичны классам для фильма, поэтому и замечания аналогичные. Изменить на интерфейс.

2022-11-13 19:38 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import javax.validation.ValidationException;
Какой класс предполагается использовать? Который импортируется или созданные в пакете exception ValidationException? Если импортируемый, то созданный класс ValidationException необходимо удалить.

2022-11-13 20:50 UTC, NastasyaRosh commented
Внесла изменения и отправила новый вариант.

2022-11-13 20:55 UTC, NastasyaRosh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import javax.validation.ValidationException;
Решила использовать импортируемый, а свой удалить

2022-11-13 21:18 UTC, NastasyaRosh commented
Внесла изменения и отправила новый вариант.
Правда комментарий на яндекс практикуме заметила после того как запушила, поэтому дозалила еще раз с нормальным комментарием к коммиту о том, что сделано :)

2022-11-14 06:59 UTC, sergeymamonov approved these changes

2022-11-14 06:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> allFilms() {
Лучше сначала размешать в классе публичные методы, а затем приватные.

2022-11-14 06:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> allFilms() {
Лучше возвращать List. Collection - слишком общий интерфейс, в нем может быть и массив, и множестве и так далее.

2022-11-14 19:34 UTC, merged