Спринт 10
NastasyaRosh/java-filmorate pull request #2
Opened 2022-11-29 15:29 UTC by NastasyaRosh

-refactor существующий ранее код разбит на хранилища (service, controller и тп) -refactor добавлены зависимости через spring
-feat добавлена функция добавления друзей и постановки лайков фильмам

2022-11-30 19:25 UTC, sergeymamonov requested changes

2022-11-30 19:25 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            count = 10;
Лучше стараться числа выносить из кода в константы, переменные и так далее. Плюс дав информативное название константе, вы помогаете читающему понять, какой смысл у этого числа.

2022-11-30 19:25 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.allFilms().stream().sorted((f1, f2) -> (f2.getLikes().size() - f1.getLikes().size())).limit(count).collect(Collectors.toList());
Стараются ограничивать длину строки не более 120 символов. И если больше, то переносят на следующую. Для юзеров аналогично.

2022-11-30 19:25 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        validate(film);
Валидация должна быть в сервисе, а не в слое хранения данных.

2022-11-30 19:25 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        forNullName(user);
Лучше перенести в сервисе эту операцию.

2022-11-30 19:25 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (checkEmail(user.getEmail()).isPresent()) {
Валидацию тоже в сервис.

2022-11-30 21:10 UTC, NastasyaRosh commented
Спасибо за комментарии :)
Направляю исправленную версию.

2022-12-01 04:40 UTC, sergeymamonov approved these changes

2022-12-01 04:40 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                sorted((f1, f2) -> (f2.getLikes().size() - f1.getLikes().size())).
Дело вкуса, но чаще встречаю написание, когда строка с методом начинается с точки.
.sorted()
.limit()
.collect()

2022-12-01 04:40 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +import java.util.*;
На мой взгляд, лучше явно прописывать классы, которые импортируются.

2022-12-01 08:50 UTC, merged